package com.kamboji.quiver.ai.agent

import android.content.Context
import com.kamboji.quiver.ai.engine.InferenceEngines
import org.json.JSONArray
import org.json.JSONObject
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * The "hybrid" brain: prompts the local model to emit a JSON plan of tool calls,
 * then deterministically parses and executes them against the mini-app stores.
 * Content the user asks for (recipes, lists, instructions) is generated by the
 * model into tool arguments; the dates, execution and side effects are handled
 * in code so they're reliable even when the model is small.
 */
class QuiverAgent(
    private val app: Context,
    private val modelPath: String,
) {
    private val tools = AgentTools(app)

    data class Result(val reply: String)

    /** Runs one request end-to-end, reporting progress through [progress]. */
    suspend fun run(userText: String, progress: (String) -> Unit): Result {
        progress("Thinking…")
        // Grammar constrains GGUF decoding to valid tool-call JSON (ignored by
        // the MediaPipe engine, which can't take a grammar).
        val grammar = runCatching {
            app.assets.open("quiver_tools.gbnf").bufferedReader().use { it.readText() }
        }.getOrNull()
        val engine = InferenceEngines.create(app, modelPath, grammar)
        val raw = try {
            buildString { engine.generate(prompt(userText)).collect { append(it) } }
        } finally {
            engine.close()
        }

        val plan = extractJson(raw)
        val reply = plan?.optString("reply")?.takeIf { it.isNotBlank() }
        val steps = plan?.optJSONArray("steps") ?: JSONArray()

        if (steps.length() == 0) {
            // No actions — treat as a plain chat answer.
            return Result(reply ?: raw.trim().ifBlank { "Done." })
        }

        val done = mutableListOf<String>()
        for (i in 0 until steps.length()) {
            val step = steps.optJSONObject(i) ?: continue
            val toolName = step.optString("tool")
            val tool = tools.byName(toolName)
            val args = step.optJSONObject("args") ?: JSONObject()
            if (tool == null) { done += "⚠️ Unknown action “$toolName”"; continue }
            progress("Working: ${tool.name}…")
            val res = runCatching { tool.run(args) }.getOrElse { ToolResult(false, "Failed: ${it.message}") }
            done += (if (res.ok) "✓ " else "⚠️ ") + res.message
        }

        val summary = buildString {
            append(reply ?: "Done.")
            append("\n\n")
            append(done.joinToString("\n"))
        }
        return Result(summary)
    }

    private fun prompt(userText: String): String {
        val now = LocalDateTime.now()
        val date = now.format(DateTimeFormatter.ISO_LOCAL_DATE)
        val dow = now.dayOfWeek.name.lowercase().replaceFirstChar { it.uppercase() }
        val time = now.format(DateTimeFormatter.ofPattern("HH:mm"))
        val zone = ZoneId.systemDefault().id
        return """
            You are Quiver AI, a helpful assistant inside a phone app. You can perform actions by calling tools.

            Available tools:
            ${tools.specText()}

            Context: today is $date ($dow), the current time is $time, timezone $zone.

            When the user asks you to do something, reply with ONLY a JSON object, no prose and no markdown fences, in exactly this shape:
            {"reply":"<short friendly confirmation for the user>","steps":[{"tool":"<tool name>","args":{ ... }}]}

            Rules:
            - Resolve relative dates yourself from today's date. Use "date":"YYYY-MM-DD" and 24h "time":"HH:mm". Dayparts: morning=09:00, afternoon=14:00, evening=18:00, night=20:00.
            - Generate any requested content (recipes, ingredient lists, instructions) yourself and put it inside the tool arguments. Checklist items are lines like "- [ ] item".
            - You may use several steps in order. To add content under an existing note, use append_note.
            - If no action is needed (just chatting), return "steps":[] and put your answer in "reply".
            - Output JSON only.

            Example user: "Save a shopping list of tomatoes and pasta, and remind me tomorrow evening to buy them."
            Example output:
            {"reply":"Saved your shopping list and a reminder for tomorrow evening.","steps":[{"tool":"add_note","args":{"title":"Shopping list","body":"- [ ] Tomatoes\n- [ ] Pasta"}},{"tool":"add_task","args":{"title":"Buy groceries","date":"$date","time":"18:00"}}]}

            User: $userText
            JSON:
        """.trimIndent()
    }

    /** Pulls the outermost {...} object out of a possibly-noisy model response. */
    private fun extractJson(raw: String): JSONObject? {
        val start = raw.indexOf('{')
        val end = raw.lastIndexOf('}')
        if (start < 0 || end <= start) return null
        return runCatching { JSONObject(raw.substring(start, end + 1)) }.getOrNull()
    }
}
